#!/usr/bin/env bash

PORT=8000

if [ ! -z "$1" ]; then
    PORT=$1
fi

echo "Starting gunicorn on port ${PORT}..."

export PYTHONPATH=$(pwd)/../../

gunicorn -w 1 --bind 0.0.0.0:${PORT} main:talk.app.server
